config/routes.rb
Bookmarks::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:update, :show]

  resources :bookmarks, only: [:index, :edit, :destroy, :update] do
    resources :likes, only: [:create, :destroy]
  end
  resources :tags, only: [:show]
  
  post :incoming, to: 'incoming#create'
  
  get 'about' => 'welcome#about'
  root to: 'welcome#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :likes, dependent: :destroy

  default_scope {order('created_at DESC')}
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :bookmarks

  default_scope {order('created_at DESC')}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookmarks
  has_many :likes, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end

  def role?(base_role)
    role == base_role.to_s
  end

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
    @tags = Tag.all
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark

    if @bookmark.update_attributes(bookmark_params)
      redirect_to bookmarks_path, notice: "Bookmark sucessfully saved."
    else
      render :new, error: "There was an error saving your bookmark. Please try again."
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    url = @bookmark.url

    authorize @bookmark

    if @bookmark.destroy
      redirect_to bookmarks_path, notice: "Bookmark for \"#{url}\" was deleted successfully."
    else
      redirect_to bookmarks_path, error: "There was an error deleying the bookmark."
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    email = params[:sender]
    subject = params[:subject]
    body = params['body-plain']
    url = /\b(([\w-]+:\/\/?|www[.])[^\s()<>]+(?:\([\w\d]+\)|([^[:punct:]\s]|\/)))/i.match(body)[1]

    # lookup user by email
    @user = User.find_by_email(email)

    # if email in User db, then create and add bookmark
    if @user.id

      # create and associate bookmark to user
      @bookmark = @user.bookmarks.build()

      # split subject to seperate tags into array and reject any empty tags
      @tags = subject.scan(/#+[a-zA-Z0-9]*/i).map{|e| e.gsub(/#/,'')}


      # associate tags with @bookmark
      @tags.each do |tag|
        # build new tag
        t = Tag.where(label: tag).first_or_create
        @bookmark.tags << t
      end

      # Add URL to bookmark
      @bookmark.url = url

      @bookmark.save
    end

    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)
    authorize like

    if like.save
      redirect_to bookmarks_path, notice: "Bookmark liked."
    else
      redirect_to bookmarks_path, error: "The was an error saving the like. Please try again."
    end    
  end

  def destroy
    like = current_user.likes.find(params[:id])
    authorize like

    if like.destroy
      redirect_to bookmarks_path, notice: "Bookmark unliked."
    else
      redirect_to bookmarks_path, error: "The was an error deleting the like. Please try again."
    end    
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @bookmarks = @tag.bookmarks
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @bookmarks = current_user.bookmarks.all
    @tags = user_tags
    @likes = tag_contains_likes
  end

  def update
    if current_user.update_attributes(user_params)
      redirect_to edit_user_registration_path, notice: "User information updated."
    else
      render "devise/registrations/edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def user_tag_ids
    @bookmarks.map do |b|
      b.tags.pluck(:id)
    end
  end

  def user_tags
    # Unique tags only
    tag_ids_array = user_tag_ids.flatten.uniq

    tag_ids_array.map do |tag_id|
      Tag.find(tag_id)
    end
  end

  def user_liked_tag_ids
    @likes.map do |like|
      like.bookmark.id
    end
  end

  def tag_contains_likes
    all_tags = Tag.all
    tag_contains_liked_bookmark = []

    all_tags.map do |tag|
      # check if tag contains liked bookmarks and add to array
      if current_user.likes.find_by(bookmark_id: tag.bookmarks.map(&:id))
        tag_contains_liked_bookmark << tag.id
      end
    end

    tag_contains_liked_bookmark.reject
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.haml
= form_for [bookmark] do |form|
  - if bookmark.errors.any?
    .alert.alert-danger
      %h4 There are #{pluralize(bookmark.errors.count, "error")}
      %ul
        - bookmark.errors.full_messages.each do |msg|
          %li= msg

  .col-md-6
    .form-group
      = form.label :url
      = form.text_field :url, autofocus: true, class: 'form-control', placeholder: 'Enter url'

    .form-group
      = form.submit 'Save', class: 'btn btn-success'

app/views/bookmarks/edit.html.haml
%h1 Edit Bookmark
.row
  .col-md-12
    .row
      = render partial: 'form', locals: {bookmark: @bookmark}

app/views/bookmarks/index.html.haml
- embedly_api = Embedly::API.new :key => ENV['EMBEDLY_KEY'], :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'

%h1 Bookmarks
- @tags.each do |tag|
  .media
    .media-body
      %h4.media-heading= link_to "##{tag.label}", tag
      .row
        - tag.bookmarks.each_with_index do |bookmark, index|
          - if index < 4
            - url = bookmark.url
            - obj = embedly_api.extract :url => url
            .col-md-6
              .row.preview-container
                %a{href: url, target: '_blank'}
                  .col-md-4.preview-image
                    %div
                      = image_tag(obj.first.images[0]['url'])
                  .col-md-8.preview-info
                    %div
                      %h3= truncate(obj.first.title, length: 50)
                      %p= truncate(obj.first.description, length: 175)
              = render partial: 'likes/like', locals: {bookmark: bookmark}
      - if tag.bookmarks.length > 4
        = link_to "More &#10145;".html_safe, tag

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Bookmarks
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Home", root_path
        %li= link_to "About", about_path
        %li= link_to "Bookmarks", bookmarks_path
        - if current_user
          %li= link_to "My Bookmarks", user_path(current_user)
          %li= link_to "Profile", edit_user_registration_path

        .pull-right.user-info
          - if current_user
            Welcome back #{(current_user.name || current_user.email)}! #{link_to "Sign out", destroy_user_session_path, method: :delete}
          - else
            #{link_to "Sign In", new_user_session_path} or #{link_to "Sign Up", new_user_registration_path}
      - if flash[:notice]
        %br
        .alert.alert-success
          %button.close{type: "button", data: {dismiss: "alert"}} &times;
          = flash[:notice]
      - elsif flash[:error]
        %br
        .alert.alert-danger
          %button.close{type: "button", data: {dismiss: "alert"}} &times;
          = flash[:error]
      - elsif flash[:alert]
        %br
        .alert.alert-warning
          %button.close{type: "button", data: {dismiss: "alert"}} &times;
          = flash[:alert]
      = yield

app/views/likes/_like.html.haml
- if current_user
  - like = current_user.likes.find_by_bookmark_id(bookmark)
  - if like
    = link_to "Unlike", bookmark_like_path(bookmark, like), method: :delete
  - else
    = link_to "Like", bookmark_likes_path(bookmark), method: :post

app/views/tags/show.html.haml
- embedly_api = Embedly::API.new :key => ENV['EMBEDLY_KEY'], :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'

%h1= "##{@tag.label}"
.media
  .media-body
    .row
      - @bookmarks.each do |bookmark|
        - url = bookmark.url
        - obj = embedly_api.extract :url => url
        .col-md-6
          .row.preview-container
            %a{href: url, target: '_blank'}
              .col-md-4.preview-image
                %div
                  = image_tag(obj.first.images[0]['url'])
              .col-md-8.preview-info
                %div
                  %h3= truncate(obj.first.title, length: 50)
                  %p= truncate(obj.first.description, length: 175)
          = render partial: 'likes/like', locals: {bookmark: bookmark}

app/views/users/show.html.haml
- embedly_api = Embedly::API.new :key => ENV['EMBEDLY_KEY'], :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'

%h1 My Bookmarks
- @tags.each do |tag|
  .media
    .media-body
      %h4.media-heading= link_to "##{tag.label}", tag
      .row
        - tag.bookmarks.each do |bookmark|
          - if current_user.id == bookmark.user_id
            - url = bookmark.url
            - obj = embedly_api.extract :url => url
            .col-md-6
              .row.preview-container
                %a{href: url, target: '_blank'}
                  .col-md-4.preview-image
                    %div
                      = image_tag(obj.first.images[0]['url'])
                  .col-md-8.preview-info
                    %div
                      %h3= truncate(obj.first.title, length: 50)
                      %p= truncate(obj.first.description, length: 175)
              - if policy(bookmark).edit?
                = link_to "Edit", edit_bookmark_path(bookmark)
                = " | "
                = link_to "Delete", bookmark, method: :delete, data: {confirm: 'Are you sure you want to delete this bookmark?'}

- if current_user.likes.count > 0
  %h2 Liked Bookmarks
  - @likes.each do |i|
    .media
      .media-body
        %h4.media-heading= link_to "##{Tag.find_by(id: i).label}", Tag.find_by(id: i)
        .row
          - Tag.find_by(id: i).bookmarks.each do |bookmark|
            - if current_user.liked(bookmark)
              - url = bookmark.url
              - obj = embedly_api.extract :url => url
              .col-md-6
                .row.preview-container
                  %a{href: url, target: '_blank'}
                    .col-md-4.preview-image
                      %div
                        = image_tag(obj.first.images[0]['url'])
                    .col-md-8.preview-info
                      %div
                        %h3= truncate(obj.first.title, length: 50)
                        %p= truncate(obj.first.description, length: 175)
                = render partial: 'likes/like', locals: {bookmark: bookmark}

app/views/welcome/about.html.haml
%h1 About Bookmarks
%p Bookmarks is a social web application that allows users to bookmark URLs via email and maintain a personal index of categorized bookmarks. In addition, members are able to browse and “like” other user’s bookmarks which allows them to share and discover new sites with friends and family.
%h2 Want to try it out?
%p To experience the full features of this application you will need to sign up. Fortunately it's really easy and free. Here are some quick instuctions:
%ol
  %li Simply sign up for a free account (Use your email or Facebook account)
  %li Login to your personal email (the one you used to sign up with)
  %li Compose a new email
  %li Add a hashtag (i.e. #lifehacks) to the subject line
  %li Include a URL in the body of your email (i.e. http://lifehacker.com/)
  %li Send an email to Bookmarks at postmaster@app28761010.mailgun.org
  %li Login to your new Bookmarks account and enjoy!
%p Don't want to sign up? No prob. If you are interested in test-driving Bookmarks login using the following cedentials:
%ul.list-unstyled
  %li U: member@example.com
  %li P: helloworld
%p You will not be able to add new bookmarks, but you can "Like" other users bookmarks.
%h2 Want to see more?
%p If you are interested in or have any questions about my work, please visit my site at <a href="http://www.soriafernando.com/" target="_blank">www.soriafernando.com</a>.

app/views/welcome/index.html.haml
%br
.jumbotron
  %h1 Bookmarks
  %p Bookmarks allows users to bookmark URLs via email, peruse other user's bookmarks and maintain a personal index of categorized bookmarks.
  %p #{link_to "Sign In", new_user_session_path, class: 'btn btn-primary'} or #{link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'} today!